# Generated by Django 4.1.13 on 2023-12-31 08:04

import animals.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('animal_type', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('breed', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Adopted', 'Adopted')], max_length=255)),
                ('animal_profile', models.FileField(upload_to=animals.models.upload_animal_image)),
                ('registered_on', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=animals.models.upload_multiple_animal_images)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
            ],
            options={
                'verbose_name': 'Additional Image for the Animal',
                'verbose_name_plural': 'Additional Images for the Animals',
            },
        ),
        migrations.CreateModel(
            name='AnimalBehaviour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behaviour', models.CharField(max_length=255)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('temperament_score', models.PositiveIntegerField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('In Review', 'In Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=256)),
                ('reason', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RescuedTable',
            fields=[
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='animals.animal')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Rescued', 'Rescued')], max_length=255)),
                ('rescue_time', models.DateTimeField(auto_now_add=True)),
                ('rescuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
