# Generated by Django 4.1.13 on 2023-12-31 08:32

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_profile',
            field=models.FileField(null=True, upload_to=animals.models.upload_animal_image),
        ),
    ]
