# Generated by Django 4.1.13 on 2023-12-31 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animal_animal_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimages',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animals.animal'),
        ),
    ]
