# Generated by Django 4.1.13 on 2023-12-31 11:23

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animalimages_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimages',
            name='image',
            field=models.FileField(upload_to=animals.models.upload_multiple_animal_images),
        ),
    ]
