# Generated by Django 4.1.13 on 2024-01-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_alter_animalimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuedtable',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Rescued', 'Rescued')], default='Submitted', max_length=255),
        ),
    ]
