# Generated by Django 4.1.13 on 2024-01-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_alter_adoptionapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuedtable',
            name='location',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='rescuedtable',
            name='reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
