# Generated by Django 4.1.13 on 2024-01-01 05:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(null=True, upload_to=accounts.models.user_image_path),
        ),
    ]
