# Generated by Django 4.1.13 on 2024-01-01 06:08

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chatroom_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_id',
            field=models.CharField(default=chats.models.generateRandomID, max_length=6),
        ),
    ]
